server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongodb:27017/ordersdb}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}